Refine arguments' types for error interceptors
axios/axios pull request #2729
Opened 2020-02-10 16:02 UTC by xamgore

That PR is an improved solution for #2553.

2020-02-10 22:14 UTC, ahuglajbclajep commented
`AxiosError` now accepts type arguments in #1738.
Therefore, it may be better to set `AxiosError` to `AxiosError<V>`.

2020-02-11 11:50 UTC, xamgore commented
@ahuglajbclajep wow, thanks! I have squashed all commits into one.

2020-06-22 12:47 UTC, xamgore commented
@Alanscut @chinesedfan could you please review the PR?

2020-10-01 00:50 UTC, forgo commented
What happened to this?

2021-01-07 10:35 UTC, barakplasma commented
doesn't the return type of the interceptor have to be the same error?

2021-01-07 15:13 UTC, barakplasma approved these changes
looks good to me

2021-01-07 15:13 UTC, barakplasma commented on index.d.ts
> +  use(onFulfilled?: (value: V) => V | Promise<V>, onRejected?: (error: AxiosError<V> | any) => any): number;
```suggestion
  use(onFulfilled?: (value: V) => V | Promise<V>, onRejected?: (error: AxiosError<V> | any) => Promise<any>): number;
```

2021-01-07 15:15 UTC, barakplasma requested changes
I think we should make one more little change while we're working on this.

2021-01-18 11:08 UTC, barakplasma approved these changes
Great

2021-09-05 10:17 UTC, jasonsaayman commented
Can you please check the merge config? If not I will close this for now and we can reopen.

2021-09-16 18:45 UTC, closed without merging