Fixing README.md
axios/axios pull request #3818
Opened 2021-05-30 06:20 UTC by snamiki1212

In config code, fixed missing comma and using incorrectly semicolon instead of a comma.

2021-06-21 07:22 UTC, hsh2001 requested changes

2021-06-21 07:22 UTC, hsh2001 commented on README.md
> +    clarifyTimeoutError: false
```suggestion
    clarifyTimeoutError: false,
```
See about [trailing commas](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas)

2021-06-22 06:03 UTC, snamiki1212 commented
> continuous-integration/travis-ci Expected — Waiting for status to be reported

CI appears to not work so I tried to do following process but still not work.

- force commit to update
- Re-create PR(https://github.com/axios/axios/pull/3847)

How should I solve this?

2021-06-25 12:39 UTC, hg-pyun approved these changes
LGTM

2021-08-13 12:57 UTC, merged