chore: added transport to RawAxiosRequestConfig
axios/axios pull request #5445
Opened 2023-01-07 14:05 UTC by Cadienvan

Related, yet separated from #5444 , added transport property to the RawAxiosRequestConfig. As it isn't checked in input, can't really provide anything but `any`.

2023-03-06 09:30 UTC, Cadienvan commented
I'm pretty sure there was a flaky test, it isn't related to my commit.

Can someone re-run tests?

2023-04-07 22:52 UTC, yanfaliupst commented
bump? I'm also looking for this field and I would like it to be in the d.ts file as it's documented on the README.md. Thanks

2023-04-07 23:13 UTC, DigitalBrainJS requested changes

2023-04-07 23:13 UTC, DigitalBrainJS commented on index.d.ts
> +  transport?: any;
This line must also be added to [index.d.сts](https://github.com/axios/axios/blob/v1.x/index.d.cts) in order to have consistent types for the CommonJS module.

2023-04-10 16:33 UTC, yanfaliupst commented on index.d.ts
> +  transport?: any;
@Cadienvan bump?

2023-04-10 16:44 UTC, Cadienvan commented on index.d.ts
> +  transport?: any;
Yep I'll do it tomorrow sorry guys it's Easter days 🤣

2023-04-11 07:12 UTC, Cadienvan commented
There you go @DigitalBrainJS @yanfaliupst   :)

2023-04-13 21:44 UTC, DigitalBrainJS approved these changes

2023-04-13 21:45 UTC, merged

2023-04-13 23:40 UTC, yanfaliupst commented
Thanks so much!