Acknowledging the pull request feature.
axios/axios pull request #6191
Opened 2024-01-18 01:24 UTC by SauravGhm

#### Instructions

Please read and follow the instructions before creating and submitting a pull request:

- Create an issue explaining the feature. It could save you some effort in case we don't consider it should be included in axios.
- If you're fixing a bug, try to commit the failing test/s and the code fixing it in different commits.
- Ensure you're following our [contributing guide](https://github.com/axios/axios/blob/master/CONTRIBUTING.md).

**⚠️👆 Delete the instructions before submitting the pull request 👆⚠️**

Describe your pull request here.

2024-01-18 05:30 UTC, WillianAgostini requested changes
replace 'the the' to 'the'

2024-01-18 15:08 UTC, SauravGhm commented
> replace 'the the' to 'the'

done ! Thankyou

2024-01-18 15:27 UTC, WillianAgostini approved these changes

2024-02-16 10:15 UTC, closed without merging

2024-02-16 10:16 UTC, jasonsaayman commented
thanks for the contribution but i don think this is the correct wording to make the change however since you have pointed that out i will fix it and others up in the code base